// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFHpzJxFSiiskk0lJOK-jVxtkSgAqkE4',
    appId: '1:201414172775:web:71180c52f7574e387cb4c2',
    messagingSenderId: '201414172775',
    projectId: 'education-7804e',
    authDomain: 'education-7804e.firebaseapp.com',
    storageBucket: 'education-7804e.firebasestorage.app',
    measurementId: 'G-3P1HDDPC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhoRCSrTmOtaTuPz-15lO6RG9OepjautY',
    appId: '1:201414172775:android:933799b91355c7c97cb4c2',
    messagingSenderId: '201414172775',
    projectId: 'education-7804e',
    storageBucket: 'education-7804e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBqM722zQXkgzKwqL8BtZdo598KBXILk',
    appId: '1:201414172775:ios:c25fd69dced6560c7cb4c2',
    messagingSenderId: '201414172775',
    projectId: 'education-7804e',
    storageBucket: 'education-7804e.firebasestorage.app',
    iosBundleId: 'com.example.education',
  );
}
